version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: financiera-app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: your_database
      DB_USERNAME: root
      DB_PASSWORD: secret

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: your_database
